#ifndef COLORS_H
#define COLORS_H

typedef enum {
    COLOR_BLACK,
    COLOR_WHITE,
    COLOR_GRAY,
    COLOR_LIGHT_GRAY,
    COLOR_DARK_GRAY,

    COLOR_RED,
    COLOR_LIGHT_RED,
    COLOR_DARK_RED,

    COLOR_GREEN,
    COLOR_LIGHT_GREEN,
    COLOR_DARK_GREEN,

    COLOR_BLUE,
    COLOR_LIGHT_BLUE,
    COLOR_DARK_BLUE,

    COLOR_YELLOW,
    COLOR_LIGHT_YELLOW,
    COLOR_DARK_YELLOW,

    COLOR_CYAN,
    COLOR_LIGHT_CYAN,
    COLOR_DARK_CYAN,

    COLOR_MAGENTA,
    COLOR_LIGHT_MAGENTA,
    COLOR_DARK_MAGENTA,

    COLOR_BROWN,
    COLOR_ORANGE,
    COLOR_PINK,
    COLOR_BEIGE,
    COLOR_TEAL,
    COLOR_NAVY,
    COLOR_OLIVE,
    COLOR_MAROON,
    COLOR_GOLD,
    COLOR_SILVER
} Color;

unsigned int getColorCode(Color c);

#endif